apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu-requests-remover-webhook
  namespace: cpu-requests-remover-webhook
  labels:
    app: cpu-requests-remover-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cpu-requests-remover-webhook
  template:
    metadata:
      labels:
        app: cpu-requests-remover-webhook
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: cpu-requests-remover-webhook
        image: bentastic27/cpu-requests-remover-webhook:latest
        ports:
        - containerPort: 8443
          name: https
        args:
        - "--workers=8"
        - "--access-logfile=-"
        - "--log-file=-"
        - "--certfile=/certs/tls.crt"
        - "--keyfile=/certs/tls.key"
        - "--bind=0.0.0.0:8443"
        - "app:app"
        readinessProbe:
          httpGet:
            path: /health
            scheme: HTTPS
            port: 8443
          initialDelaySeconds: 3
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            scheme: HTTPS
            port: 8443
          initialDelaySeconds: 3
        volumeMounts:
        - readOnly: true
          mountPath: /certs
          name: certs
      volumes:
        - name: certs
          secret:
            secretName: cpu-requests-remover-webhook-cert
