kind: MutatingWebhookConfiguration
apiVersion: admissionregistration.k8s.io/v1
metadata:
  name: cpu-requests-remover-webhook
webhooks:
- name: cpu-requests-remover-webhook.cpu-requests-remover-webhook.svc
  sideEffects: NoneOnDryRun
  failurePolicy: Ignore
  admissionReviewVersions:
  - v1
  rules:
  - operations: ["CREATE", "UPDATE"]
    apiGroups: ["*"]
    apiVersions: ["v1"]
    resources: ["pods"]
  clientConfig:
    service:
      namespace: cpu-requests-remover-webhook
      name: cpu-requests-remover-webhook
      path: /mutate
      port: 80
