kind: MutatingWebhookConfiguration
apiVersion: admissionregistration.k8s.io/v1
metadata:
  name: cpu-requests-remover-webhook
webhooks:
- name: cpu-requests-remover-webhook.cpu-requests-remover-webhook.svc
  rules:
  - operations: ["CREATE", "UPDATE"]
    apiGroups: ["*"]
    apiVersions: ["v1"]
    resources: ["Pod"]
  clientConfig:
    service:
      namespace: cpu-requests-remover-webhook
      name: cpu-requests-remover-webhook
      path: /mutate
