name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'config/**'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'config/**'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            bentastic27/cpu-requests-remover-webhook:${{ github.sha }}
            bentastic27/cpu-requests-remover-webhook:latest
